#!/bin/bash

#SBATCH --account=researchers
#SBATCH --job-name=writeout
#SBATCH --output=logs/R-%x.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=logs/R-%x.%j.err     # Error handling
#SBATCH --nodes=1                # Total number of nodes requested
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --mem=48G
#SBATCH --time=0-02:00:00          # Run time (hh:mm:ss) 
#SBATCH --partition=red,brown    # Run on either the red or brown queue

#srun hostname

module load Anaconda3
source activate lmeval_thesis
conda env list

python write_out.py "lambada_openai,paws_en,hellaswag" --num_fewshot 0 --num_examples 10 output_path "write_out"
